USE ucode_web_uevent;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Comment;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS Comment(
    Comment_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    User_ID INT NOT NULL,
    Event_ID INT NOT NULL,
    FOREIGN KEY(User_ID) REFERENCES User(User_ID),
    FOREIGN KEY(Event_ID) REFERENCES Event(Event_ID)
);