USE ucode_web_uevent;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Event_Theme;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS Event_Theme(
    Event_ID INT NOT NULL,
    Theme_ID INT NOT NULL,
    FOREIGN KEY(Event_ID) REFERENCES Event(Event_ID),
    FOREIGN KEY(Theme_ID) REFERENCES Theme(Theme_ID)
)