USE ucode_web_uevent;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Formate;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS Formate(
    Formate_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description VARCHAR(255)
)