USE ucode_web_uevent;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Format;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS Format(
    Format_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL
)