USE ucode_web_uevent;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Rating;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS Rating(
    Rating_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    score INT,
    User_ID INT NOT NULL,
    FOREIGN KEY(User_ID) REFERENCES User(User_ID),
    Event_ID INT NOT NULL,
    FOREIGN KEY(Event_ID) REFERENCES Event(Event_ID)
);
